# Generated by Django 5.2 on 2025-06-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('produce', '0002_alter_farmproduce_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerprofile',
            name='preferred_products',
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='preferred_products',
            field=models.ManyToManyField(to='produce.crop'),
        ),
    ]
