# Generated by Django 5.2 on 2025-06-19 22:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_buyerprofile_preferred_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='group_formation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Formation Date'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='group_members_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Members'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='group_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Group/Cooperative Name'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='group_registration_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Registration Number'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='is_group',
            field=models.BooleanField(default=False, verbose_name='Farmer Group/Cooperative'),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='farm_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='farm_size_unit',
            field=models.CharField(blank=True, choices=[('acres', 'Acres'), ('hectares', 'Hectares'), ('sqm', 'Square Meters')], default='acres', max_length=10),
        ),
    ]
