# Generated by Django 5.2 on 2025-06-20 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_farmerprofile_contact_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='expected_harvest_date',
        ),
    ]
