# Generated by Django 5.2 on 2025-06-19 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmproduce',
            options={'ordering': ['-listed_at'], 'verbose_name': 'FarmProduce Listing', 'verbose_name_plural': 'FarmProduce Listings'},
        ),
    ]
